# Generated by Django 4.1.3 on 2022-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NextTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_color', models.CharField(max_length=40)),
                ('route_id', models.IntegerField()),
                ('timeTillNextTrain', models.IntegerField()),
            ],
        ),
    ]
