# Generated by Django 4.1.3 on 2022-11-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_color', models.CharField(max_length=40)),
                ('route_id', models.IntegerField(default=999)),
                ('timeTillNextTrain', models.IntegerField(default=999)),
            ],
        ),
        migrations.DeleteModel(
            name='NextTrain',
        ),
    ]
