# Generated by Django 4.1.3 on 2022-11-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_train_delete_nexttrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField(default=2)),
                ('numLegs', models.IntegerField(default=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
